apiVersion: v1
kind: Secret
metadata:
  name: ignored-sample-secret
  namespace: replicator-sample-namespace
type: Opaque
data:
  testKey3: dGVzdFZhbDM= #gitleaks:allow
  testKey4: dGVzdFZhbDM= #gitleaks:allow
