name: Branch Build

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build Branch
        uses: ./.github/workflows/build.yaml
        with:
            publish-snapshots: true
        secrets:
            docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
